version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
build_script:
- ps: .\build.ps1
deploy:
- provider: NuGet
  api_key:
    secure: cjUFAKvz0TqOrRFYhnuiEspsrFKeRr1xdfS2H4YY2THW2JZ+tCwHVQxYqLm+UZ33
  on:
    appveyor_repo_tag: true