version: 1.0.{build}
image: Visual Studio 2017
build_script:
- ps: .\build.ps1
deploy:
- provider: NuGet
  api_key:
    secure: hukFrKl6aHI/QyMM4I47WR/rpi3n01lfSK66Np5G3EvBl+KYRcjfNREEhBy73r8o
  on:
    appveyor_repo_tag: true