#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Cheesebaron.SlidingUpPanel.Resource", IsApplication=false)]

namespace Cheesebaron.SlidingUpPanel
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int collapsedHeight = 2130771968;
			
			// aapt resource value: 0x7f010004
			public static int dragView = 2130771972;
			
			// aapt resource value: 0x7f010002
			public static int fadeColor = 2130771970;
			
			// aapt resource value: 0x7f010003
			public static int flingVelocity = 2130771971;
			
			// aapt resource value: 0x7f010005
			public static int overlay = 2130771973;
			
			// aapt resource value: 0x7f010001
			public static int shadowHeight = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int above_shadow = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SlidingUpPanelLayout = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public static int SlidingUpPanelLayout_collapsedHeight = 0;
			
			// aapt resource value: 4
			public static int SlidingUpPanelLayout_dragView = 4;
			
			// aapt resource value: 2
			public static int SlidingUpPanelLayout_fadeColor = 2;
			
			// aapt resource value: 3
			public static int SlidingUpPanelLayout_flingVelocity = 3;
			
			// aapt resource value: 5
			public static int SlidingUpPanelLayout_overlay = 5;
			
			// aapt resource value: 1
			public static int SlidingUpPanelLayout_shadowHeight = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
